server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888
ribbon:
  eureka:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  service-name: Eureka Service
  service-version: v1.0
eureka:
  instance:
    hostname: localhost