spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sarpio_transaction
    username: AnatoliiHamza
    password: 123Anatolii
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  liquibase:
    change-log: 'classpath:liquibase/liquibase-changeLog.xml'

eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  swagger-ui:
    path: /sw



